### ISSUE TITLE
Generate an icon from the mesh

### ISSUE THREAD

**Issue by idbrii** [Frontrider/Godot-Component-Browser#4]
> There is a default icon for your components, but you can place a png file with the same name as the scene in the same folder to use that (if the scene is res://assets/components/example/example_component.tscn, the image should be res://assets/components/example/example_component.png), and it will be displayed instead.

I thought it was going to generate an icon for each component, but I could override it with my own. But maybe it means there's [one default icon](https://github.com/Frontrider/Godot-Scene-Browser/blob/master/addons/component_view/assets/default.png) that's used for all assets?

Would be awesome to generate icons for assets!

Edit: Looks like the code is using `get_editor_interface().make_mesh_previews()`, so it **should** be generating icons, but it's silently failing for me.

I'm using 3e256ac437901cddd5ea62802accb4749f00c9d4 with Godot 3.5.1.stable and [Kenney's city-kit-suburban](https://kenney.nl/assets/city-kit-suburban).

**Comment by Frontrider** [comment]
I saw that happening before but supposed to be fixed. I'll take a look as soon as I can.

**Comment by Frontrider** [comment]
Format?

**Comment by Frontrider** [comment]
I think I know what it will be, I'll update the readme tomorrow.

**Comment by idbrii** [comment]
I used the glb files in that asset pack. Thanks for investigating!

**Comment by Frontrider** [comment]
I remember what it was, partially updated the readme and added a wiki page to the repository. I won't close this yet, I want your feedback on that.

**Comment by Frontrider** [comment]
After a second peek, one condition is missing.
https://github.com/Frontrider/Godot-Scene-Browser/blob/7be890d96988331e101a8600c7f0c20d3eb07d20/addons/component_view/import_scripts/ImportPipeline.gd#L10

At this line, I specifically check if it found an empty mesh or not, because sometimes when importing an asset as a scene that can happen. I don't know why, but it does. So you have to check if the mesh is empty or not, and skip it if it is.
